apiVersion: v1
kind: Pod
metadata:
  name: failing-pod
spec:
  containers:
    - name: failing-pod
      image: busybox
      args:
        - /bin/sh
        - -c
        - |
          while true; do
            echo $(date) >> ~/tmp/curr-date.txt
            sleep 5
          done

